name: Build and Test

on:
  pull_request:
  push:
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_call:

env:
  ARTIFACT_NAME: bb-rsync

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      artifact_file: ${{ env.ARTIFACT_NAME }}

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
        experimental:
          - false
        include:
          - toolchain: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust/Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
